/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MotoviagensRouteImport } from './routes/motoviagens'
import { Route as DolphinDicasRouteImport } from './routes/dolphin-dicas'
import { Route as AryzRouteImport } from './routes/aryz'
import { Route as IndexRouteImport } from './routes/index'

const MotoviagensRoute = MotoviagensRouteImport.update({
  id: '/motoviagens',
  path: '/motoviagens',
  getParentRoute: () => rootRouteImport,
} as any)
const DolphinDicasRoute = DolphinDicasRouteImport.update({
  id: '/dolphin-dicas',
  path: '/dolphin-dicas',
  getParentRoute: () => rootRouteImport,
} as any)
const AryzRoute = AryzRouteImport.update({
  id: '/aryz',
  path: '/aryz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aryz': typeof AryzRoute
  '/dolphin-dicas': typeof DolphinDicasRoute
  '/motoviagens': typeof MotoviagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aryz': typeof AryzRoute
  '/dolphin-dicas': typeof DolphinDicasRoute
  '/motoviagens': typeof MotoviagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aryz': typeof AryzRoute
  '/dolphin-dicas': typeof DolphinDicasRoute
  '/motoviagens': typeof MotoviagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aryz' | '/dolphin-dicas' | '/motoviagens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aryz' | '/dolphin-dicas' | '/motoviagens'
  id: '__root__' | '/' | '/aryz' | '/dolphin-dicas' | '/motoviagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AryzRoute: typeof AryzRoute
  DolphinDicasRoute: typeof DolphinDicasRoute
  MotoviagensRoute: typeof MotoviagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/motoviagens': {
      id: '/motoviagens'
      path: '/motoviagens'
      fullPath: '/motoviagens'
      preLoaderRoute: typeof MotoviagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dolphin-dicas': {
      id: '/dolphin-dicas'
      path: '/dolphin-dicas'
      fullPath: '/dolphin-dicas'
      preLoaderRoute: typeof DolphinDicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aryz': {
      id: '/aryz'
      path: '/aryz'
      fullPath: '/aryz'
      preLoaderRoute: typeof AryzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AryzRoute: AryzRoute,
  DolphinDicasRoute: DolphinDicasRoute,
  MotoviagensRoute: MotoviagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
